"""add data_range to bin_summary

Revision ID: 007b70f21474
Revises: 9bbff2262eeb
Create Date: 2026-03-20 14:19:16.569097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '007b70f21474'
down_revision: Union[str, Sequence[str], None] = '9bbff2262eeb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bin_summary', sa.Column('data_range', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bin_summary', 'data_range')
    # ### end Alembic commands ###
