"""add product_mappings

Revision ID: 078861c7181f
Revises: bda1ee8512d0
Create Date: 2026-03-19 17:07:21.812965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '078861c7181f'
down_revision: Union[str, Sequence[str], None] = 'bda1ee8512d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('program_prefix', sa.String(), nullable=True),
    sa.Column('product_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_mappings_id'), 'product_mappings', ['id'], unique=False)
    op.create_index(op.f('ix_product_mappings_program_prefix'), 'product_mappings', ['program_prefix'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_mappings_program_prefix'), table_name='product_mappings')
    op.drop_index(op.f('ix_product_mappings_id'), table_name='product_mappings')
    op.drop_table('product_mappings')
    # ### end Alembic commands ###
