"""add ftp scan snapshots table

Revision ID: 1ca516947112
Revises: ca19106c1773
Create Date: 2026-07-09 02:41:35.985748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ca516947112'
down_revision: Union[str, Sequence[str], None] = 'ca19106c1773'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('system_settings', 'alarm_email')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('system_settings', sa.Column('alarm_email', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
