"""Add comment to bin_summary

Revision ID: 30a7f2112187
Revises: 5fd377541678
Create Date: 2026-04-14 21:40:12.276098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30a7f2112187'
down_revision: Union[str, Sequence[str], None] = '5fd377541678'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bin_summary', sa.Column('comment', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bin_summary', 'comment')
    # ### end Alembic commands ###
