"""Add original summary columns to Lot

Revision ID: 5fd377541678
Revises: 007b70f21474
Create Date: 2026-03-21 21:37:29.497626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fd377541678'
down_revision: Union[str, Sequence[str], None] = '007b70f21474'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lots', sa.Column('original_die_count', sa.Integer(), nullable=True))
    op.add_column('lots', sa.Column('original_pass_count', sa.Integer(), nullable=True))
    op.add_column('lots', sa.Column('original_fail_count', sa.Integer(), nullable=True))
    op.add_column('lots', sa.Column('original_yield_rate', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lots', 'original_yield_rate')
    op.drop_column('lots', 'original_fail_count')
    op.drop_column('lots', 'original_pass_count')
    op.drop_column('lots', 'original_die_count')
    # ### end Alembic commands ###
