"""add_role_remove_is_admin

Revision ID: 7bf097043e4a
Revises: a1b2c3d4e5f6
Create Date: 2026-05-20 05:48:54.769962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bf097043e4a'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.String(), nullable=True))
    
    # 迁移数据：保留现有的管理员
    op.execute("UPDATE users SET role = 'admin' WHERE is_admin = true")
    op.execute("UPDATE users SET role = 'user' WHERE is_admin = false OR is_admin IS NULL")
    
    op.add_column('users', sa.Column('email_verified', sa.Boolean(), nullable=True, server_default=sa.text('false')))
    op.drop_column('users', 'is_admin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_admin', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('users', 'email_verified')
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
