"""add_mp_tester_probecard_to_lots

Revision ID: 91e1112b0a63
Revises: 84fd42d52e85
Create Date: 2026-06-01 09:12:17.049248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91e1112b0a63'
down_revision: Union[str, Sequence[str], None] = '84fd42d52e85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lots', sa.Column('mp_tester', sa.String(), nullable=True))
    op.add_column('lots', sa.Column('probecard', sa.String(), nullable=True))
    op.add_column('lots', sa.Column('osat_name', sa.String(), nullable=True))
    op.create_index(op.f('ix_lots_osat_name'), 'lots', ['osat_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lots_osat_name'), table_name='lots')
    op.drop_column('lots', 'osat_name')
    op.drop_column('lots', 'probecard')
    op.drop_column('lots', 'mp_tester')
    # ### end Alembic commands ###
