"""add site to test_items

Revision ID: bda1ee8512d0
Revises: 3deb42c05f70
Create Date: 2026-03-19 15:40:01.401569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bda1ee8512d0'
down_revision: Union[str, Sequence[str], None] = '3deb42c05f70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_items', sa.Column('site', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_items', 'site')
    # ### end Alembic commands ###
