"""add_protocol_to_osat_configs

Revision ID: ca19106c1773
Revises: d4e5f6a7b8c9
Create Date: 2026-06-23 09:19:02.127034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca19106c1773'
down_revision: Union[str, Sequence[str], None] = 'd4e5f6a7b8c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('osat_configs', sa.Column('protocol', sa.String(), server_default='ftp', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('osat_configs', 'protocol')
    # ### end Alembic commands ###
